version: '3.8'

services:
  mongodb:
    image: mongo:latest  # This will pull the latest stable MongoDB version
    container_name: nestjs-mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
